update new codebase
Signed-off-by: The-Repo-Club <wayne6324@gmail.com>

diff --git a/snaphome b/snaphome
--- a/snaphome
+++ b/snaphome
@@ -1,8 +1,30 @@
 #!/usr/bin/env bash
+#-*-coding:utf-8 -*-
+#Auto updated?
+#   Yes
+#File :
+#   snaphome
+#Author :
+#   The-Repo-Club [wayne6324@gmail.com]
+#Github :
+#   https://github.com/The-Repo-Club/
+#
+#Created:
+#   Sun 17 July 2022, 11:02:22 PM [GMT+1]
+#Last edited:
+#   Sun 17 July 2022, 11:15:05 PM [GMT+1]
+#
+#Description:
+#   <Todo>
+#
+#Dependencies:
+#   <None>
+#
+
 set -e
 
-SNAP_HOME=$(gsettings get org.therepoclub.btrfs-snapshots.preferences home | sed s/\'//g)
-SNAP_PACMAN=$(gsettings get org.therepoclub.btrfs-snapshots.preferences pacman | sed s/\'//g)
+SNAP_HOME=$(snapexec home | sed s/\'//g)
+SNAP_PACMAN=$(snapexec pacman | sed s/\'//g)
 
 ## Script metadata
 SCRIPTNAME=${0##*/}
@@ -29,8 +51,9 @@ readonly ALL_OFF RED GREEN YELLOW BLUE PURPLE CYAN
 
 # copied from makepkg
 error() {
-    local mesg=$1; shift
-    printf "${RED}==> ERROR:${ALL_OFF}${BOLD} %s${ALL_OFF}\n" "$mesg" "$@" >&2
+  local mesg=$1
+  shift
+  printf "${RED}==> ERROR:${ALL_OFF}${BOLD} %s${ALL_OFF}\n" "$mesg" "$@" >&2
 }
 
 #=== FUNCTION =================================================================
@@ -39,104 +62,105 @@ error() {
 #==============================================================================
 
 main() {
-    #number of snapshots allowed
-    sn=$SNAP_HOME
+  #number of snapshots allowed
+  sn=$SNAP_HOME
 
-    runas=$(whoami)
+  runas=$(whoami)
 
-    if [ $runas != 'root' ]; then
-        printf ${GREEN}"%s ${RED}command must be ran as root\n" "$SCRIPTNAME"
-        exit
+  if [ $runas != 'root' ]; then
+    printf ${GREEN}"%s ${RED}command must be ran as root\n" "$SCRIPTNAME"
+    exit
+  fi
+
+  #home subvolume device
+  hsvdvl=1
+  while IFS= read -r Line; do
+    if [ -n "$hsvdvl" ]; then
+      unset hsvdvl
+      continue
     fi
+    set -- $Line
+    [ "$2" = 'btrfs' ] && [ "${7}" = '/home' ] && hsvdv="$1"
+  done <<<$(df -Th)
 
-    #home subvolume device
-    hsvdvl=1
-    while IFS= read -r Line; do
-	    if [ -n "$hsvdvl" ]; then
-		    unset hsvdvl; continue
-	    fi
-	    set -- $Line
-	    [ "$2" = 'btrfs' ] && [ "${7}" = '/home' ] && hsvdv="$1"
-    done <<< $( df -Th )
+  #current date
+  cdt=$(date +"%F-%H-%M-%S")
 
-    #current date
-    cdt=`date +"%F-%H-%M-%S"`
+  #home subvolume
+  while IFS= read -r Line; do
+    set -- $Line
+    [ "$7" = '5' ] && [ "$9" = '@home' ] && hsv="${@: -1}"
+  done <<<$(btrfs subvolume list /)
 
-    #home subvolume
-    while IFS= read -r Line; do
-	    set -- $Line
-	    [ "$7" = '5' ] && [ "$9" = '@home' ] && hsv="${@: -1}"
-    done <<< $( btrfs subvolume list / )
+  #snapshot subvolume
+  while IFS= read -r Line; do
+    set -- $Line
+    [ "$7" = '5' ] && [ "$9" = '@snapshots' ] && ssv="${@: -1}"
+  done <<<$(btrfs subvolume list /)
 
-    #snapshot subvolume
-    while IFS= read -r Line; do
-	    set -- $Line
-	    [ "$7" = '5' ] && [ "$9" = '@snapshots' ] && ssv="${@: -1}"
-    done <<< $( btrfs subvolume list / )
+  #number of home snapshots
+  hsl=0
+  while IFS= read -r Line; do
+    LastColumn=${Line##* }
+    [ "${LastColumn:0:16}" = '@snapshots/@home' ] && [ "${LastColumn:16:7}" != '-pacman' ] && hsl=$((hsl + 1))
+  done <<<$(btrfs subvolume list /)
 
-    #number of home snapshots
-    hsl=0
-    while IFS= read -r Line; do
-	    LastColumn=${Line##* }
-	    [ "${LastColumn:0:16}" = '@snapshots/@home' ] && [ "${LastColumn:16:7}" != '-pacman' ] && hsl=$((hsl+1))
-    done <<< $( btrfs subvolume list / )
+  #oldest home snapshot
+  while IFS= read -r Line; do
+    LastColumn=${Line##* }
+    [ "${LastColumn:0:16}" = '@snapshots/@home' ] && [ "${LastColumn:16:7}" != '-pacman' ] && ohs="$LastColumn" && break
+  done <<<$(btrfs subvolume list /)
 
-    #oldest home snapshot
-    while IFS= read -r Line; do
-	    LastColumn=${Line##* }
-	    [ "${LastColumn:0:16}" = '@snapshots/@home' ] && [ "${LastColumn:16:7}" != '-pacman' ] && ohs="$LastColumn" && break
-    done <<< $( btrfs subvolume list / )
+  #Mount home subvolume to /mnt/750GB/.snapshots
+  mnt='/mnt/750GB/.snapshots'
 
-    #Mount home subvolume to /mnt/750GB/.snapshots
-    mnt='/mnt/750GB/.snapshots'
-
-    if [ -e "$hsvdv" ]; then
-        if [ -d "$mnt" ]; then
-            printf "${YELLOW}Mounted $hsvdv to $mnt${ALL_OFF}\n"
-        else
-            printf "${RED}No btrfs drives found${ALL_OFF}\n"
-            exit 1
-        fi
+  if [ -e "$hsvdv" ]; then
+    if [ -d "$mnt" ]; then
+      printf "${YELLOW}Mounted $hsvdv to $mnt${ALL_OFF}\n"
     else
-        printf "${RED}No btrfs drives found${ALL_OFF}\n"
-        exit 1
+      printf "${RED}No btrfs drives found${ALL_OFF}\n"
+      exit 1
     fi
+  else
+    printf "${RED}No btrfs drives found${ALL_OFF}\n"
+    exit 1
+  fi
 
-    #MUST be in /mnt to perform task
-    cd $mnt
+  #MUST be in /mnt to perform task
+  cd $mnt
 
+  # Check home subvolume exists...
+  if [ -e "$hsv" ]; then
+    printf "${GREEN}Found home subvolume... $hsv${ALL_OFF}\n"
+  else
+    printf "${RED}No home subvolume found... exiting${ALL_OFF}\n"
+    exit 1
+  fi
 
-    # Check home subvolume exists...
-    if [ -e "$hsv" ]; then
-        printf "${GREEN}Found home subvolume... $hsv${ALL_OFF}\n"
-    else
-        printf "${RED}No home subvolume found... exiting${ALL_OFF}\n"
-        exit 1
-    fi
+  # check snapshot subvolume exists...
+  if [ -e "$ssv" ]; then
+    printf "${GREEN}Found snapshot suvolume... $ssv${ALL_OFF}\n"
+  else
+    printf "${RED}No snapshot subvolume found${ALL_OFF}\n"
 
-    # check snapshot subvolume exists...
-    if [ -e "$ssv" ]; then
-        printf "${GREEN}Found snapshot suvolume... $ssv${ALL_OFF}\n"
-    else
-        printf "${RED}No snapshot subvolume found${ALL_OFF}\n"
+    exit 1
+  fi
 
-        exit 1
-    fi
+  #Make snapshot and place in snapshot directory
+  btrfs subvolume snapshot $hsv $ssv/@home-$cdt
 
-    #Make snapshot and place in snapshot directory
-    btrfs subvolume snapshot $hsv $ssv/@home-$cdt
+  #remove a home snapshot if there are more than 5
+  if [ "$hsl" -ge "$sn" ]; then
+    printf "${RED}Removing oldest $hsv snapshot... $ohs${ALL_OFF}\n"
+    btrfs subvolume delete $ohs
+  else
+    printf "${YELLOW}Not enough $hsv snapshots...${ALL_OFF}\n"
+    printf "${YELLOW}No snapshots to delete...${ALL_OFF}\n"
+  fi
 
-    #remove a home snapshot if there are more than 5
-    if [ "$hsl" -ge "$sn" ]; then
-        printf "${RED}Removing oldest $hsv snapshot... $ohs${ALL_OFF}\n"
-        btrfs subvolume delete $ohs
-    else
-        printf "${YELLOW}Not enough $hsv snapshots...${ALL_OFF}\n"
-        printf "${YELLOW}No snapshots to delete...${ALL_OFF}\n"
-    fi
-
-    printf "\n"
-    read -rsn1 -p "Press any key to continue";printf "\n"
+  printf "\n"
+  read -rsn1 -p "Press any key to continue"
+  printf "\n"
 }
 
 #=== FUNCTION =================================================================
@@ -145,104 +169,105 @@ main() {
 #==============================================================================
 
 pacman() {
-    #number of snapshots allowed
-    sn=$SNAP_PACMAN
+  #number of snapshots allowed
+  sn=$SNAP_PACMAN
 
-    runas=$(whoami)
+  runas=$(whoami)
 
-    if [ $runas != 'root' ]; then
-        printf ${GREEN}"%s ${RED}command must be ran as root\n" "$SCRIPTNAME"
-        exit
+  if [ $runas != 'root' ]; then
+    printf ${GREEN}"%s ${RED}command must be ran as root\n" "$SCRIPTNAME"
+    exit
+  fi
+
+  #home subvolume device
+  hsvdvl=1
+  while IFS= read -r Line; do
+    if [ -n "$hsvdvl" ]; then
+      unset hsvdvl
+      continue
     fi
+    set -- $Line
+    [ "$2" = 'btrfs' ] && [ "${7}" = '/home' ] && hsvdv="$1"
+  done <<<$(df -Th)
 
-    #home subvolume device
-    hsvdvl=1
-    while IFS= read -r Line; do
-	    if [ -n "$hsvdvl" ]; then
-		    unset hsvdvl; continue
-	    fi
-	    set -- $Line
-	    [ "$2" = 'btrfs' ] && [ "${7}" = '/home' ] && hsvdv="$1"
-    done <<< $( df -Th )
+  #current date
+  cdt=$(date +"%F-%H-%M-%S")
 
-    #current date
-    cdt=`date +"%F-%H-%M-%S"`
+  #home subvolume
+  while IFS= read -r Line; do
+    set -- $Line
+    [ "$7" = '5' ] && [ "$9" = '@home' ] && hsv="${@: -1}"
+  done <<<$(btrfs subvolume list /)
 
-    #home subvolume
-    while IFS= read -r Line; do
-	    set -- $Line
-	    [ "$7" = '5' ] && [ "$9" = '@home' ] && hsv="${@: -1}"
-    done <<< $( btrfs subvolume list / )
+  #snapshot subvolume
+  while IFS= read -r Line; do
+    set -- $Line
+    [ "$7" = '5' ] && [ "$9" = '@snapshots' ] && ssv="${@: -1}"
+  done <<<$(btrfs subvolume list /)
 
-    #snapshot subvolume
-    while IFS= read -r Line; do
-	    set -- $Line
-	    [ "$7" = '5' ] && [ "$9" = '@snapshots' ] && ssv="${@: -1}"
-    done <<< $( btrfs subvolume list / )
+  #number of home snapshots
+  hsl=0
+  while IFS= read -r Line; do
+    LastColumn=${Line##* }
+    [ "${LastColumn:0:23}" = '@snapshots/@home-pacman' ] && hsl=$((hsl + 1))
+  done <<<$(btrfs subvolume list /)
 
-    #number of home snapshots
-    hsl=0
-    while IFS= read -r Line; do
-	    LastColumn=${Line##* }
-	    [ "${LastColumn:0:23}" = '@snapshots/@home-pacman' ] && hsl=$((hsl+1))
-    done <<< $( btrfs subvolume list / )
+  #oldest home snapshot
+  while IFS= read -r Line; do
+    LastColumn=${Line##* }
+    [ "${LastColumn:0:23}" = '@snapshots/@home-pacman' ] && ohs="$LastColumn" && break
+  done <<<$(btrfs subvolume list /)
 
-    #oldest home snapshot
-    while IFS= read -r Line; do
-	    LastColumn=${Line##* }
-	    [ "${LastColumn:0:23}" = '@snapshots/@home-pacman' ] && ohs="$LastColumn" && break
-    done <<< $( btrfs subvolume list / )
+  #Mount home subvolume to /mnt/750GB/.snapshots
+  mnt='/mnt/750GB/.snapshots'
 
-    #Mount home subvolume to /mnt/750GB/.snapshots
-    mnt='/mnt/750GB/.snapshots'
-
-    if [ -e "$hsvdv" ]; then
-        if [ -d "$mnt" ]; then
-            printf "${YELLOW}Mounted $hsvdv to $mnt${ALL_OFF}\n"
-        else
-            printf "${RED}No btrfs drives found${ALL_OFF}\n"
-            exit 1
-        fi
+  if [ -e "$hsvdv" ]; then
+    if [ -d "$mnt" ]; then
+      printf "${YELLOW}Mounted $hsvdv to $mnt${ALL_OFF}\n"
     else
-        printf "${RED}No btrfs drives found${ALL_OFF}\n"
-        exit 1
+      printf "${RED}No btrfs drives found${ALL_OFF}\n"
+      exit 1
     fi
+  else
+    printf "${RED}No btrfs drives found${ALL_OFF}\n"
+    exit 1
+  fi
 
-    #MUST be in /mnt to perform task
-    cd $mnt
+  #MUST be in /mnt to perform task
+  cd $mnt
 
+  # Check home subvolume exists...
+  if [ -e "$hsv" ]; then
+    printf "${GREEN}Found home subvolume... $hsv${ALL_OFF}\n"
+  else
+    printf "${RED}No home subvolume found... exiting${ALL_OFF}\n"
+    exit 1
+  fi
 
-    # Check home subvolume exists...
-    if [ -e "$hsv" ]; then
-        printf "${GREEN}Found home subvolume... $hsv${ALL_OFF}\n"
-    else
-        printf "${RED}No home subvolume found... exiting${ALL_OFF}\n"
-        exit 1
-    fi
+  # check snapshot subvolume exists...
+  if [ -e "$ssv" ]; then
+    printf "${GREEN}Found snapshot suvolume... $ssv${ALL_OFF}\n"
+  else
+    printf "${RED}No snapshot subvolume found${ALL_OFF}\n"
 
-    # check snapshot subvolume exists...
-    if [ -e "$ssv" ]; then
-        printf "${GREEN}Found snapshot suvolume... $ssv${ALL_OFF}\n"
-    else
-        printf "${RED}No snapshot subvolume found${ALL_OFF}\n"
+    exit 1
+  fi
 
-        exit 1
-    fi
+  #Make snapshot and place in snapshot directory
+  btrfs subvolume snapshot $hsv $ssv/@home-pacman-$cdt
 
-    #Make snapshot and place in snapshot directory
-    btrfs subvolume snapshot $hsv $ssv/@home-pacman-$cdt
+  #remove a home snapshot if there are more than 5
+  if [ "$hsl" -ge "$sn" ]; then
+    printf "${RED}Removing oldest $hsv snapshot... $ohs${ALL_OFF}\n"
+    btrfs subvolume delete $ohs
+  else
+    printf "${YELLOW}Not enough $hsv snapshots...${ALL_OFF}\n"
+    printf "${YELLOW}No snapshots to delete...${ALL_OFF}\n"
+  fi
 
-    #remove a home snapshot if there are more than 5
-    if [ "$hsl" -ge "$sn" ]; then
-        printf "${RED}Removing oldest $hsv snapshot... $ohs${ALL_OFF}\n"
-        btrfs subvolume delete $ohs
-    else
-        printf "${YELLOW}Not enough $hsv snapshots...${ALL_OFF}\n"
-        printf "${YELLOW}No snapshots to delete...${ALL_OFF}\n"
-    fi
-
-    printf "\n"
-    read -rsn1 -p "Press any key to continue";printf "\n"
+  printf "\n"
+  read -rsn1 -p "Press any key to continue"
+  printf "\n"
 }
 
 #=== FUNCTION =================================================================
@@ -251,14 +276,14 @@ pacman() {
 #==============================================================================
 
 version() {
-    printf "
+  printf "
         %s v%s - %s
 
         This program may be freely redistributed under
         the terms of the GNU General Public License v3.0.
         %s
     \n" "$SCRIPTNAME" "$VERSION" "$DESCRIPTION" "$AUTHOR"
-    exit
+  exit
 }
 
 #=== FUNCTION =================================================================
@@ -268,7 +293,7 @@ version() {
 
 usage() {
 
-    printf "
+  printf "
     Snapshot the @ and @home btrfs subvolumes.
     Usage:
       %s...
@@ -281,31 +306,31 @@ usage() {
 }
 
 while true; do
-    case $1 in
-        -h|--help|-\?)
-            usage
-            exit 0
-            ;;
-        -v|--version)
-            version
-            exit 0
-            ;;
-        -p|--pacman)
-            pacman
-            exit 0
-            ;;
-        --)
-            shift
-            break
-            ;;
-        -*)
-            error "Unknown option: $1"
-            usage
-            exit 1
-            ;;
-        *)
-            main
-            break
-            ;;
-    esac
+  case $1 in
+  -h | --help | -\?)
+    usage
+    exit 0
+    ;;
+  -v | --version)
+    version
+    exit 0
+    ;;
+  -p | --pacman)
+    pacman
+    exit 0
+    ;;
+  --)
+    shift
+    break
+    ;;
+  -*)
+    error "Unknown option: $1"
+    usage
+    exit 1
+    ;;
+  *)
+    main
+    break
+    ;;
+  esac
 done
diff --git a/snaplist b/snaplist
--- a/snaplist
+++ b/snaplist
@@ -1,4 +1,26 @@
 #!/usr/bin/env bash
+#-*-coding:utf-8 -*-
+#Auto updated?
+#   Yes
+#File :
+#   snaplist
+#Author :
+#   The-Repo-Club [wayne6324@gmail.com]
+#Github :
+#   https://github.com/The-Repo-Club/
+#
+#Created:
+#   Sun 17 July 2022, 11:03:43 PM [GMT+1]
+#Last edited:
+#   Sun 17 July 2022, 11:03:48 PM [GMT+1]
+#
+#Description:
+#   <Todo>
+#
+#Dependencies:
+#   <None>
+#
+
 ## Script metadata
 SCRIPTNAME=${0##*/}
 VERSION="2021.09.19"
@@ -24,8 +46,9 @@ readonly ALL_OFF RED GREEN YELLOW BLUE PURPLE CYAN
 
 # copied from makepkg
 error() {
-    local mesg=$1; shift
-    printf "${RED}==> ERROR:${ALL_OFF}${BOLD} %s${ALL_OFF}\n" "$mesg" "$@" >&2
+  local mesg=$1
+  shift
+  printf "${RED}==> ERROR:${ALL_OFF}${BOLD} %s${ALL_OFF}\n" "$mesg" "$@" >&2
 }
 
 #=== FUNCTION =================================================================
@@ -33,72 +56,73 @@ error() {
 # Description: The main function if nothing is passed
 #==============================================================================
 
-main(){
-    runas=$(whoami)
+main() {
+  runas=$(whoami)
 
-    if [ $runas != 'root' ]; then
-        printf ${GREEN}"%s ${RED}command must be ran as root\n" "$SCRIPTNAME"
-        exit
+  if [ $runas != 'root' ]; then
+    printf ${GREEN}"%s ${RED}command must be ran as root\n" "$SCRIPTNAME"
+    exit
+  fi
+
+  IndexOf() {
+    x="${1%%$2*}"
+    [ "$x" = "$1" ] || printf '%d' "${#x}"
+  }
+
+  declare -A PathCounts
+  declare -A Paths
+  NL='\n'
+
+  while IFS= read -r Line; do
+
+    set -- $Line
+
+    # Path is after the first "path "
+    Path=$9
+
+    # Get the index of the first /
+    PathL2Index=$(IndexOf "$Path" '/')
+
+    # Ignore paths that don't have a 2nd level
+    [ -z "$PathL2Index" ] && continue
+
+    Id=$2
+
+    # Path is after the first / in Path
+    PathL2=${Path:$((PathL2Index + 1))}
+
+    # Remove the 10 char date from the end to isolate the name
+    NameL2=${PathL2%????????????????????}
+
+    # Remove the 1st character "@"
+    NameL2=${NameL2:1}
+
+    # If -pacman exists in the NameL2, it's category is pacman
+    if [ "${NameL2##*-pacman}" = "$1" ]; then
+      Category='pacman'
+    else
+      Category=$NameL2
     fi
 
-    IndexOf() {
-        x="${1%%$2*}"
-        [ "$x" = "$1" ] || printf '%d' "${#x}"
-    }
+    # Add NameL2 to appropriate category
+    Paths["$Category"]="${Paths["$Category"]}ID=$Id $Path$NL"
 
-    declare -A PathCounts
-    declare -A Paths
-    NL='\n'
+    # Increment count in appropriate category
+    ((PathCounts["$Category"]++))
 
-    while IFS= read -r Line; do
+  done <<<$(btrfs subvolume list /)
 
-        set -- $Line
+  FirstRun=1
+  for Key in "${!Paths[@]}"; do
+    [ -n "$FirstRun" ] || printf '\n'
+    printf "${GREEN}list of %s snapshots: ${YELLOW}%s${ALL_OFF}\n" "$Key" "${PathCounts[$Key]}"
+    printf "${Paths[$Key]}"
+    FirstRun=
+  done
 
-        # Path is after the first "path "
-        Path=$9
-
-        # Get the index of the first /
-        PathL2Index=$( IndexOf "$Path" '/' )
-
-        # Ignore paths that don't have a 2nd level
-        [ -z "$PathL2Index" ] && continue
-
-        Id=$2
-
-        # Path is after the first / in Path
-        PathL2=${Path:$(( PathL2Index + 1 ))}
-
-        # Remove the 10 char date from the end to isolate the name
-        NameL2=${PathL2%????????????????????}
-
-        # Remove the 1st character "@"
-        NameL2=${NameL2:1}
-
-        # If -pacman exists in the NameL2, it's category is pacman
-        if [ "${NameL2##*-pacman}" = "$1" ]; then
-            Category='pacman'
-        else
-            Category=$NameL2
-        fi
-
-        # Add NameL2 to appropriate category
-        Paths["$Category"]="${Paths["$Category"]}ID=$Id $Path$NL"
-
-        # Increment count in appropriate category
-        (( PathCounts["$Category"]++ ))
-
-    done <<< $(btrfs subvolume list /)
-
-    FirstRun=1
-    for Key in "${!Paths[@]}"; do
-        [ -n "$FirstRun" ] || printf '\n'
-        printf "${GREEN}list of %s snapshots: ${YELLOW}%s${ALL_OFF}\n" "$Key" "${PathCounts[$Key]}"
-        printf "${Paths[$Key]}";
-        FirstRun=
-    done
-
-    printf "\n"
-    read -rsn1 -p "Press any key to continue";printf "\n"
+  printf "\n"
+  read -rsn1 -p "Press any key to continue"
+  printf "\n"
 }
 
 #=== FUNCTION =================================================================
@@ -106,68 +130,68 @@ main(){
 # Description: The menu function for repomenu
 #==============================================================================
 
-menu(){
-    runas=$(whoami)
+menu() {
+  runas=$(whoami)
 
-    if [ $runas != 'root' ]; then
-        printf ${GREEN}"%s ${RED}command must be ran as root\n" "$SCRIPTNAME"
-        exit
+  if [ $runas != 'root' ]; then
+    printf ${GREEN}"%s ${RED}command must be ran as root\n" "$SCRIPTNAME"
+    exit
+  fi
+
+  IndexOf() {
+    x="${1%%$2*}"
+    [ "$x" = "$1" ] || printf '%d' "${#x}"
+  }
+
+  declare -A PathCounts
+  declare -A Paths
+  NL='\n'
+
+  while IFS= read -r Line; do
+
+    set -- $Line
+
+    # Path is after the first "path "
+    Path=$9
+
+    # Get the index of the first /
+    PathL2Index=$(IndexOf "$Path" '/')
+
+    # Ignore paths that don't have a 2nd level
+    [ -z "$PathL2Index" ] && continue
+
+    Id=$2
+
+    # Path is after the first / in Path
+    PathL2=${Path:$((PathL2Index + 1))}
+
+    # Remove the 10 char date from the end to isolate the name
+    NameL2=${PathL2%????????????????????}
+
+    # Remove the 1st character "@"
+    NameL2=${NameL2:1}
+
+    # If -pacman exists in the NameL2, it's category is pacman
+    if [ "${NameL2##*-pacman}" = "$1" ]; then
+      Category='pacman'
+    else
+      Category=$NameL2
     fi
 
-    IndexOf() {
-        x="${1%%$2*}"
-        [ "$x" = "$1" ] || printf '%d' "${#x}"
-    }
+    # Add NameL2 to appropriate category
+    Paths["$Category"]="${Paths["$Category"]}ID=$Id $Path$NL"
 
-    declare -A PathCounts
-    declare -A Paths
-    NL='\n'
+    # Increment count in appropriate category
+    ((PathCounts["$Category"]++))
 
-    while IFS= read -r Line; do
+  done <<<$(btrfs subvolume list /)
 
-        set -- $Line
-
-        # Path is after the first "path "
-        Path=$9
-
-        # Get the index of the first /
-        PathL2Index=$( IndexOf "$Path" '/' )
-
-        # Ignore paths that don't have a 2nd level
-        [ -z "$PathL2Index" ] && continue
-
-        Id=$2
-
-        # Path is after the first / in Path
-        PathL2=${Path:$(( PathL2Index + 1 ))}
-
-        # Remove the 10 char date from the end to isolate the name
-        NameL2=${PathL2%????????????????????}
-
-        # Remove the 1st character "@"
-        NameL2=${NameL2:1}
-
-        # If -pacman exists in the NameL2, it's category is pacman
-        if [ "${NameL2##*-pacman}" = "$1" ]; then
-            Category='pacman'
-        else
-            Category=$NameL2
-        fi
-
-        # Add NameL2 to appropriate category
-        Paths["$Category"]="${Paths["$Category"]}ID=$Id $Path$NL"
-
-        # Increment count in appropriate category
-        (( PathCounts["$Category"]++ ))
-
-    done <<< $(btrfs subvolume list /)
-
-    FirstRun=1
-    for Key in "${!Paths[@]}"; do
-        [ -n "$FirstRun" ] || printf ''
-        printf "${Paths[$Key]}";
-        FirstRun=
-    done
+  FirstRun=1
+  for Key in "${!Paths[@]}"; do
+    [ -n "$FirstRun" ] || printf ''
+    printf "${Paths[$Key]}"
+    FirstRun=
+  done
 }
 
 #=== FUNCTION =================================================================
@@ -176,14 +200,14 @@ menu(){
 #==============================================================================
 
 version() {
-    printf "
+  printf "
     %s v%s - %s
 
     This program may be freely redistributed under
     the terms of the GNU General Public License v3.0.
     %s
     \n" "$SCRIPTNAME" "$VERSION" "$DESCRIPTION" "$AUTHOR"
-    exit
+  exit
 }
 
 #=== FUNCTION =================================================================
@@ -193,7 +217,7 @@ version() {
 
 usage() {
 
-    printf "
+  printf "
     Snapshot the @ and @root btrfs subvolumes.
     Usage:
       %s...
@@ -206,31 +230,31 @@ usage() {
 }
 
 while true; do
-    case $1 in
-        -h|--help|-\?)
-            usage
-            exit 0
-            ;;
-        -v|--version)
-            version
-            exit 0
-            ;;
-        -m|--menu)
-            menu
-            exit 0
-            ;;
-        --)
-            shift
-            break
-            ;;
-        -*)
-            error "Unknown option: $1"
-            usage
-            exit 1
-            ;;
-        *)
-            main
-            break
-            ;;
-    esac
+  case $1 in
+  -h | --help | -\?)
+    usage
+    exit 0
+    ;;
+  -v | --version)
+    version
+    exit 0
+    ;;
+  -m | --menu)
+    menu
+    exit 0
+    ;;
+  --)
+    shift
+    break
+    ;;
+  -*)
+    error "Unknown option: $1"
+    usage
+    exit 1
+    ;;
+  *)
+    main
+    break
+    ;;
+  esac
 done
diff --git a/snaproot b/snaproot
--- a/snaproot
+++ b/snaproot
@@ -1,8 +1,30 @@
 #!/usr/bin/env bash
+#-*-coding:utf-8 -*-
+#Auto updated?
+#   Yes
+#File :
+#   snaproot
+#Author :
+#   The-Repo-Club [wayne6324@gmail.com]
+#Github :
+#   https://github.com/The-Repo-Club/
+#
+#Created:
+#   Sun 17 July 2022, 11:03:52 PM [GMT+1]
+#Last edited:
+#   Sun 17 July 2022, 11:14:55 PM [GMT+1]
+#
+#Description:
+#   <Todo>
+#
+#Dependencies:
+#   <None>
+#
+
 set -e
 
-SNAP_ROOT=$(gsettings get org.therepoclub.btrfs-snapshots.preferences root | sed s/\'//g)
-SNAP_PACMAN=$(gsettings get org.therepoclub.btrfs-snapshots.preferences pacman | sed s/\'//g)
+SNAP_ROOT=$(snapexec root | sed s/\'//g)
+SNAP_PACMAN=$(snapexec pacman | sed s/\'//g)
 
 ## Script metadata
 SCRIPTNAME=${0##*/}
@@ -29,8 +51,9 @@ readonly ALL_OFF RED GREEN YELLOW BLUE PURPLE CYAN
 
 # copied from makepkg
 error() {
-    local mesg=$1; shift
-    printf "${RED}==> ERROR:${ALL_OFF}${BOLD} %s${ALL_OFF}\n" "$mesg" "$@" >&2
+  local mesg=$1
+  shift
+  printf "${RED}==> ERROR:${ALL_OFF}${BOLD} %s${ALL_OFF}\n" "$mesg" "$@" >&2
 }
 
 #=== FUNCTION =================================================================
@@ -39,103 +62,105 @@ error() {
 #==============================================================================
 
 main() {
-    #number of snapshots allowed
-    sn=$SNAP_ROOT
+  #number of snapshots allowed
+  sn=$SNAP_ROOT
 
-    runas=$(whoami)
+  runas=$(whoami)
 
-    if [ $runas != 'root' ]; then
-        printf ${GREEN}"%s ${RED}command must be ran as root\n" "$SCRIPTNAME"
-        exit
+  if [ $runas != 'root' ]; then
+    printf ${GREEN}"%s ${RED}command must be ran as root\n" "$SCRIPTNAME"
+    exit
+  fi
+
+  #root subvolume device
+  hsvdvl=1
+  while IFS= read -r Line; do
+    if [ -n "$hsvdvl" ]; then
+      unset hsvdvl
+      continue
     fi
+    set -- $Line
+    [ "$2" = 'btrfs' ] && [ "${7}" = '/' ] && hsvdv="$1"
+  done <<<$(df -Th)
 
-    #root subvolume device
-    hsvdvl=1
-    while IFS= read -r Line; do
-	    if [ -n "$hsvdvl" ]; then
-		    unset hsvdvl; continue
-	    fi
-	    set -- $Line
-	    [ "$2" = 'btrfs' ] && [ "${7}" = '/' ] && hsvdv="$1"
-    done <<< $( df -Th )
+  #current date
+  cdt=$(date +"%F-%H-%M-%S")
 
-    #current date
-    cdt=`date +"%F-%H-%M-%S"`
+  #root subvolume
+  while IFS= read -r Line; do
+    set -- $Line
+    [ "$7" = '5' ] && [ "$9" = '@' ] && hsv="${@: -1}"
+  done <<<$(btrfs subvolume list /)
 
-    #root subvolume
-    while IFS= read -r Line; do
-	    set -- $Line
-	    [ "$7" = '5' ] && [ "$9" = '@' ] && hsv="${@: -1}"
-    done <<< $( btrfs subvolume list / )
+  #snapshot subvolume
+  while IFS= read -r Line; do
+    set -- $Line
+    [ "$7" = '5' ] && [ "$9" = '@snapshots' ] && ssv="${@: -1}"
+  done <<<$(btrfs subvolume list /)
 
-    #snapshot subvolume
-    while IFS= read -r Line; do
-	    set -- $Line
-	    [ "$7" = '5' ] && [ "$9" = '@snapshots' ] && ssv="${@: -1}"
-    done <<< $( btrfs subvolume list / )
+  #number of root snapshots
+  hsl=0
+  while IFS= read -r Line; do
+    LastColumn=${Line##* }
+    [ "${LastColumn:0:16}" = '@snapshots/@root' ] && [ "${LastColumn:16:7}" != '-pacman' ] && hsl=$((hsl + 1))
+  done <<<$(btrfs subvolume list /)
 
-    #number of root snapshots
-    hsl=0
-    while IFS= read -r Line; do
-	    LastColumn=${Line##* }
-	    [ "${LastColumn:0:16}" = '@snapshots/@root' ] && [ "${LastColumn:16:7}" != '-pacman' ] && hsl=$((hsl+1))
-    done <<< $( btrfs subvolume list / )
+  #oldest root snapshot
+  while IFS= read -r Line; do
+    LastColumn=${Line##* }
+    [ "${LastColumn:0:16}" = '@snapshots/@root' ] && [ "${LastColumn:16:7}" != '-pacman' ] && ohs="$LastColumn" && break
+  done <<<$(btrfs subvolume list /)
 
-    #oldest root snapshot
-    while IFS= read -r Line; do
-	    LastColumn=${Line##* }
-	    [ "${LastColumn:0:16}" = '@snapshots/@root' ] && [ "${LastColumn:16:7}" != '-pacman' ] && ohs="$LastColumn" && break
-    done <<< $( btrfs subvolume list / )
+  #Mount root subvolume to /mnt/750GB/.snapshots
+  mnt='/mnt/750GB/.snapshots'
 
-    #Mount root subvolume to /mnt/750GB/.snapshots
-    mnt='/mnt/750GB/.snapshots'
-
-    if [ -e "$hsvdv" ]; then
-        if [ -d "$mnt" ]; then
-            printf "${YELLOW}Mounted $hsvdv to $mnt${ALL_OFF}\n"
-        else
-            printf "${RED}No btrfs drives found${ALL_OFF}\n"
-            exit 1
-        fi
+  if [ -e "$hsvdv" ]; then
+    if [ -d "$mnt" ]; then
+      printf "${YELLOW}Mounted $hsvdv to $mnt${ALL_OFF}\n"
     else
-        printf "${RED}No btrfs drives found${ALL_OFF}\n"
-        exit 1
+      printf "${RED}No btrfs drives found${ALL_OFF}\n"
+      exit 1
     fi
+  else
+    printf "${RED}No btrfs drives found${ALL_OFF}\n"
+    exit 1
+  fi
 
-    #MUST be in /mnt to perform task
-    cd $mnt
+  #MUST be in /mnt to perform task
+  cd $mnt
 
-    # Check root subvolume exists...
-    if [ -e "$hsv" ]; then
-        printf "${GREEN}Found root subvolume... $hsv${ALL_OFF}\n"
-    else
-        printf "${RED}No root subvolume found... exiting${ALL_OFF}\n"
-        exit 1
-    fi
+  # Check root subvolume exists...
+  if [ -e "$hsv" ]; then
+    printf "${GREEN}Found root subvolume... $hsv${ALL_OFF}\n"
+  else
+    printf "${RED}No root subvolume found... exiting${ALL_OFF}\n"
+    exit 1
+  fi
 
-    # check snapshot subvolume exists...
-    if [ -e "$ssv" ]; then
-        printf "${GREEN}Found snapshot suvolume... $ssv${ALL_OFF}\n"
-    else
-        printf "${RED}No snapshot subvolume found${ALL_OFF}\n"
+  # check snapshot subvolume exists...
+  if [ -e "$ssv" ]; then
+    printf "${GREEN}Found snapshot suvolume... $ssv${ALL_OFF}\n"
+  else
+    printf "${RED}No snapshot subvolume found${ALL_OFF}\n"
 
-        exit 1
-    fi
+    exit 1
+  fi
 
-    #Make snapshot and place in snapshot directory
-    btrfs subvolume snapshot $hsv $ssv/@root-$cdt
+  #Make snapshot and place in snapshot directory
+  btrfs subvolume snapshot $hsv $ssv/@root-$cdt
 
-    #remove a root snapshot if there are more than 5
-    if [ "$hsl" -ge "$sn" ]; then
-        printf "${RED}Removing oldest $hsv snapshot... $ohs${ALL_OFF}\n"
-        btrfs subvolume delete $ohs
-    else
-        printf "${YELLOW}Not enough $hsv snapshots...${ALL_OFF}\n"
-        printf "${YELLOW}No snapshots to delete...${ALL_OFF}\n"
-    fi
+  #remove a root snapshot if there are more than 5
+  if [ "$hsl" -ge "$sn" ]; then
+    printf "${RED}Removing oldest $hsv snapshot... $ohs${ALL_OFF}\n"
+    btrfs subvolume delete $ohs
+  else
+    printf "${YELLOW}Not enough $hsv snapshots...${ALL_OFF}\n"
+    printf "${YELLOW}No snapshots to delete...${ALL_OFF}\n"
+  fi
 
-    printf "\n"
-    read -rsn1 -p "Press any key to continue";printf "\n"
+  printf "\n"
+  read -rsn1 -p "Press any key to continue"
+  printf "\n"
 }
 
 #=== FUNCTION =================================================================
@@ -144,104 +169,105 @@ main() {
 #==============================================================================
 
 pacman() {
-    #number of snapshots allowed
-    sn=$SNAP_PACMAN
+  #number of snapshots allowed
+  sn=$SNAP_PACMAN
 
-    runas=$(whoami)
+  runas=$(whoami)
 
-    if [ $runas != 'root' ]; then
-        printf ${GREEN}"%s ${RED}command must be ran as root\n" "$SCRIPTNAME"
-        exit
+  if [ $runas != 'root' ]; then
+    printf ${GREEN}"%s ${RED}command must be ran as root\n" "$SCRIPTNAME"
+    exit
+  fi
+
+  #root subvolume device
+  hsvdvl=1
+  while IFS= read -r Line; do
+    if [ -n "$hsvdvl" ]; then
+      unset hsvdvl
+      continue
     fi
+    set -- $Line
+    [ "$2" = 'btrfs' ] && [ "${7}" = '/' ] && hsvdv="$1"
+  done <<<$(df -Th)
 
-    #root subvolume device
-    hsvdvl=1
-    while IFS= read -r Line; do
-	    if [ -n "$hsvdvl" ]; then
-		    unset hsvdvl; continue
-	    fi
-	    set -- $Line
-	    [ "$2" = 'btrfs' ] && [ "${7}" = '/' ] && hsvdv="$1"
-    done <<< $( df -Th )
+  #current date
+  cdt=$(date +"%F-%H-%M-%S")
 
-    #current date
-    cdt=`date +"%F-%H-%M-%S"`
+  #root subvolume
+  while IFS= read -r Line; do
+    set -- $Line
+    [ "$7" = '5' ] && [ "$9" = '@' ] && hsv="${@: -1}"
+  done <<<$(btrfs subvolume list /)
 
-    #root subvolume
-    while IFS= read -r Line; do
-	    set -- $Line
-	    [ "$7" = '5' ] && [ "$9" = '@' ] && hsv="${@: -1}"
-    done <<< $( btrfs subvolume list / )
+  #snapshot subvolume
+  while IFS= read -r Line; do
+    set -- $Line
+    [ "$7" = '5' ] && [ "$9" = '@snapshots' ] && ssv="${@: -1}"
+  done <<<$(btrfs subvolume list /)
 
-    #snapshot subvolume
-    while IFS= read -r Line; do
-	    set -- $Line
-	    [ "$7" = '5' ] && [ "$9" = '@snapshots' ] && ssv="${@: -1}"
-    done <<< $( btrfs subvolume list / )
+  #number of root snapshots
+  hsl=0
+  while IFS= read -r Line; do
+    LastColumn=${Line##* }
+    [ "${LastColumn:0:23}" = '@snapshots/@root-pacman' ] && hsl=$((hsl + 1))
+  done <<<$(btrfs subvolume list /)
 
-    #number of root snapshots
-    hsl=0
-    while IFS= read -r Line; do
-	    LastColumn=${Line##* }
-	    [ "${LastColumn:0:23}" = '@snapshots/@root-pacman' ] && hsl=$((hsl+1))
-    done <<< $( btrfs subvolume list / )
+  #oldest root snapshot
+  while IFS= read -r Line; do
+    LastColumn=${Line##* }
+    [ "${LastColumn:0:23}" = '@snapshots/@root-pacman' ] && ohs="$LastColumn" && break
+  done <<<$(btrfs subvolume list /)
 
-    #oldest root snapshot
-    while IFS= read -r Line; do
-	    LastColumn=${Line##* }
-	    [ "${LastColumn:0:23}" = '@snapshots/@root-pacman' ] && ohs="$LastColumn" && break
-    done <<< $( btrfs subvolume list / )
+  #Mount root subvolume to /mnt/750GB/.snapshots
+  mnt='/mnt/750GB/.snapshots'
 
-    #Mount root subvolume to /mnt/750GB/.snapshots
-    mnt='/mnt/750GB/.snapshots'
-
-    if [ -e "$hsvdv" ]; then
-        if [ -d "$mnt" ]; then
-            printf "${YELLOW}Mounted $hsvdv to $mnt${ALL_OFF}\n"
-        else
-            printf "${RED}No btrfs drives found${ALL_OFF}\n"
-            exit 1
-        fi
+  if [ -e "$hsvdv" ]; then
+    if [ -d "$mnt" ]; then
+      printf "${YELLOW}Mounted $hsvdv to $mnt${ALL_OFF}\n"
     else
-        printf "${RED}No btrfs drives found${ALL_OFF}\n"
-        exit 1
+      printf "${RED}No btrfs drives found${ALL_OFF}\n"
+      exit 1
     fi
+  else
+    printf "${RED}No btrfs drives found${ALL_OFF}\n"
+    exit 1
+  fi
 
-    #MUST be in /mnt to perform task
-    cd $mnt
+  #MUST be in /mnt to perform task
+  cd $mnt
 
+  # Check root subvolume exists...
+  if [ -e "$hsv" ]; then
+    printf "${GREEN}Found root subvolume... $hsv${ALL_OFF}\n"
+  else
+    printf "${RED}No root subvolume found... exiting${ALL_OFF}\n"
+    exit 1
+  fi
 
-    # Check root subvolume exists...
-    if [ -e "$hsv" ]; then
-        printf "${GREEN}Found root subvolume... $hsv${ALL_OFF}\n"
-    else
-        printf "${RED}No root subvolume found... exiting${ALL_OFF}\n"
-        exit 1
-    fi
+  # check snapshot subvolume exists...
+  if [ -e "$ssv" ]; then
+    printf "${GREEN}Found snapshot suvolume... $ssv${ALL_OFF}\n"
+  else
+    printf "${RED}No snapshot subvolume found${ALL_OFF}\n"
 
-    # check snapshot subvolume exists...
-    if [ -e "$ssv" ]; then
-        printf "${GREEN}Found snapshot suvolume... $ssv${ALL_OFF}\n"
-    else
-        printf "${RED}No snapshot subvolume found${ALL_OFF}\n"
+    exit 1
+  fi
 
-        exit 1
-    fi
+  #Make snapshot and place in snapshot directory
+  btrfs subvolume snapshot $hsv $ssv/@root-pacman-$cdt
 
-    #Make snapshot and place in snapshot directory
-    btrfs subvolume snapshot $hsv $ssv/@root-pacman-$cdt
+  #remove a root snapshot if there are more than 5
+  if [ "$hsl" -ge "$sn" ]; then
+    printf "${RED}Removing oldest $hsv snapshot... $ohs${ALL_OFF}\n"
+    btrfs subvolume delete $ohs
+  else
+    printf "${YELLOW}Not enough $hsv snapshots...${ALL_OFF}\n"
+    printf "${YELLOW}No snapshots to delete...${ALL_OFF}\n"
+  fi
 
-    #remove a root snapshot if there are more than 5
-    if [ "$hsl" -ge "$sn" ]; then
-        printf "${RED}Removing oldest $hsv snapshot... $ohs${ALL_OFF}\n"
-        btrfs subvolume delete $ohs
-    else
-        printf "${YELLOW}Not enough $hsv snapshots...${ALL_OFF}\n"
-        printf "${YELLOW}No snapshots to delete...${ALL_OFF}\n"
-    fi
-
-    printf "\n"
-    read -rsn1 -p "Press any key to continue";printf "\n"
+  printf "\n"
+  read -rsn1 -p "Press any key to continue"
+  printf "\n"
 }
 
 #=== FUNCTION =================================================================
@@ -250,14 +276,14 @@ pacman() {
 #==============================================================================
 
 version() {
-    printf "
+  printf "
         %s v%s - %s
 
         This program may be freely redistributed under
         the terms of the GNU General Public License v3.0.
         %s
     \n" "$SCRIPTNAME" "$VERSION" "$DESCRIPTION" "$AUTHOR"
-    exit
+  exit
 }
 
 #=== FUNCTION =================================================================
@@ -267,7 +293,7 @@ version() {
 
 usage() {
 
-    printf "
+  printf "
     Snapshot the @ and @root btrfs subvolumes.
     Usage:
       %s...
@@ -280,31 +306,31 @@ usage() {
 }
 
 while true; do
-    case $1 in
-        -h|--help|-\?)
-            usage
-            exit 0
-            ;;
-        -v|--version)
-            version
-            exit 0
-            ;;
-        -p|--pacman)
-            pacman
-            exit 0
-            ;;
-        --)
-            shift
-            break
-            ;;
-        -*)
-            error "Unknown option: $1"
-            usage
-            exit 1
-            ;;
-        *)
-            main
-            break
-            ;;
-    esac
+  case $1 in
+  -h | --help | -\?)
+    usage
+    exit 0
+    ;;
+  -v | --version)
+    version
+    exit 0
+    ;;
+  -p | --pacman)
+    pacman
+    exit 0
+    ;;
+  --)
+    shift
+    break
+    ;;
+  -*)
+    error "Unknown option: $1"
+    usage
+    exit 1
+    ;;
+  *)
+    main
+    break
+    ;;
+  esac
 done
diff --git a/snapshot b/snapshot
--- a/snapshot
+++ b/snapshot
@@ -1,4 +1,26 @@
 #!/usr/bin/env bash
+#-*-coding:utf-8 -*-
+#Auto updated?
+#   Yes
+#File :
+#   snapshot
+#Author :
+#   The-Repo-Club [wayne6324@gmail.com]
+#Github :
+#   https://github.com/The-Repo-Club/
+#
+#Created:
+#   Sun 17 July 2022, 11:04:01 PM [GMT+1]
+#Last edited:
+#   Sun 17 July 2022, 11:04:06 PM [GMT+1]
+#
+#Description:
+#   <Todo>
+#
+#Dependencies:
+#   <None>
+#
+
 ## Script metadata
 SCRIPTNAME=${0##*/}
 VERSION="2021.09.19"
@@ -24,8 +46,9 @@ readonly ALL_OFF RED GREEN YELLOW BLUE PURPLE CYAN
 
 # copied from makepkg
 error() {
-    local mesg=$1; shift
-    printf "${RED}==> ERROR:${ALL_OFF}${BOLD} %s${ALL_OFF}\n" "$mesg" "$@" >&2
+  local mesg=$1
+  shift
+  printf "${RED}==> ERROR:${ALL_OFF}${BOLD} %s${ALL_OFF}\n" "$mesg" "$@" >&2
 }
 
 #=== FUNCTION =================================================================
@@ -34,40 +57,40 @@ error() {
 #==============================================================================
 
 main() {
-    runas=$(whoami)
+  runas=$(whoami)
 
-    if [ $runas != 'root' ]; then
-        printf ${GREEN}"%s ${RED}command must be ran as root${ALL_OFF}\n" "$SCRIPTNAME"
-        exit
-    fi
+  if [ $runas != 'root' ]; then
+    printf ${GREEN}"%s ${RED}command must be ran as root${ALL_OFF}\n" "$SCRIPTNAME"
+    exit
+  fi
 
+  if ! command -v snaphome &>/dev/null; then
+    printf ${RED}"snaphome could not be found${ALL_OFF}\n"
+    exit
+  else
+    printf ${GREEN}"running snaphome.${ALL_OFF}\n"
+    snaphome
+  fi
 
-    if ! command -v snaphome &> /dev/null; then
-        printf ${RED}"snaphome could not be found${ALL_OFF}\n"
-        exit
-    else
-        printf ${GREEN}"running snaphome.${ALL_OFF}\n"
-        snaphome
-    fi
+  if ! command -v snaproot &>/dev/null; then
+    printf ${RED}"snaproot could not be found${ALL_OFF}\n"
+    exit
+  else
+    printf ${GREEN}"running snaproot.${ALL_OFF}\n"
+    snaproot
+  fi
 
-    if ! command -v snaproot &> /dev/null; then
-        printf ${RED}"snaproot could not be found${ALL_OFF}\n"
-        exit
-    else
-        printf ${GREEN}"running snaproot.${ALL_OFF}\n"
-        snaproot
-    fi
+  if ! command -v grub-mkconfig &>/dev/null; then
+    printf ${RED}"grub-mkconfig could not be found${ALL_OFF}\n"
+    exit
+  else
+    printf ${GREEN}"running grub-mkconfig.${ALL_OFF}\n"
+    grub-mkconfig -o /boot/grub/grub.cfg
+  fi
 
-    if ! command -v grub-mkconfig &> /dev/null; then
-        printf ${RED}"grub-mkconfig could not be found${ALL_OFF}\n"
-        exit
-    else
-        printf ${GREEN}"running grub-mkconfig.${ALL_OFF}\n"
-        grub-mkconfig -o /boot/grub/grub.cfg
-    fi
-
-    printf "\n"
-    read -rsn1 -p "Press any key to continue";printf "\n"
+  printf "\n"
+  read -rsn1 -p "Press any key to continue"
+  printf "\n"
 }
 
 #=== FUNCTION =================================================================
@@ -76,32 +99,32 @@ main() {
 #==============================================================================
 
 home_only() {
-    runas=$(whoami)
+  runas=$(whoami)
 
-    if [ $runas != 'root' ]; then
-        printf ${GREEN}"%s ${RED}command must be ran as root${ALL_OFF}\n" "$SCRIPTNAME"
-        exit
-    fi
+  if [ $runas != 'root' ]; then
+    printf ${GREEN}"%s ${RED}command must be ran as root${ALL_OFF}\n" "$SCRIPTNAME"
+    exit
+  fi
 
+  if ! command -v snaphome &>/dev/null; then
+    printf ${RED}"snaphome could not be found${ALL_OFF}\n"
+    exit
+  else
+    printf ${GREEN}"running snaphome.${ALL_OFF}\n"
+    snaphome
+  fi
 
-    if ! command -v snaphome &> /dev/null; then
-        printf ${RED}"snaphome could not be found${ALL_OFF}\n"
-        exit
-    else
-        printf ${GREEN}"running snaphome.${ALL_OFF}\n"
-        snaphome
-    fi
+  if ! command -v grub-mkconfig &>/dev/null; then
+    printf ${RED}"grub-mkconfig could not be found${ALL_OFF}\n"
+    exit
+  else
+    printf ${GREEN}"running grub-mkconfig.${ALL_OFF}\n"
+    grub-mkconfig -o /boot/grub/grub.cfg
+  fi
 
-    if ! command -v grub-mkconfig &> /dev/null; then
-        printf ${RED}"grub-mkconfig could not be found${ALL_OFF}\n"
-        exit
-    else
-        printf ${GREEN}"running grub-mkconfig.${ALL_OFF}\n"
-        grub-mkconfig -o /boot/grub/grub.cfg
-    fi
-
-    printf "\n"
-    read -rsn1 -p "Press any key to continue";printf "\n"
+  printf "\n"
+  read -rsn1 -p "Press any key to continue"
+  printf "\n"
 }
 
 #=== FUNCTION =================================================================
@@ -110,32 +133,32 @@ home_only() {
 #==============================================================================
 
 root_only() {
-    runas=$(whoami)
+  runas=$(whoami)
 
-    if [ $runas != 'root' ]; then
-        printf ${GREEN}"%s ${RED}command must be ran as root${ALL_OFF}\n" "$SCRIPTNAME"
-        exit
-    fi
+  if [ $runas != 'root' ]; then
+    printf ${GREEN}"%s ${RED}command must be ran as root${ALL_OFF}\n" "$SCRIPTNAME"
+    exit
+  fi
 
+  if ! command -v snaproot &>/dev/null; then
+    printf ${RED}"snaproot could not be found${ALL_OFF}\n"
+    exit
+  else
+    printf ${GREEN}"running snaproot.${ALL_OFF}\n"
+    snaproot
+  fi
 
-    if ! command -v snaproot &> /dev/null; then
-        printf ${RED}"snaproot could not be found${ALL_OFF}\n"
-        exit
-    else
-        printf ${GREEN}"running snaproot.${ALL_OFF}\n"
-        snaproot
-    fi
+  if ! command -v grub-mkconfig &>/dev/null; then
+    printf ${RED}"grub-mkconfig could not be found${ALL_OFF}\n"
+    exit
+  else
+    printf ${GREEN}"running grub-mkconfig.${ALL_OFF}\n"
+    grub-mkconfig -o /boot/grub/grub.cfg
+  fi
 
-    if ! command -v grub-mkconfig &> /dev/null; then
-        printf ${RED}"grub-mkconfig could not be found${ALL_OFF}\n"
-        exit
-    else
-        printf ${GREEN}"running grub-mkconfig.${ALL_OFF}\n"
-        grub-mkconfig -o /boot/grub/grub.cfg
-    fi
-
-    printf "\n"
-    read -rsn1 -p "Press any key to continue";printf "\n"
+  printf "\n"
+  read -rsn1 -p "Press any key to continue"
+  printf "\n"
 }
 
 #=== FUNCTION =================================================================
@@ -144,40 +167,40 @@ root_only() {
 #==============================================================================
 
 pacman() {
-    runas=$(whoami)
+  runas=$(whoami)
 
-    if [ $runas != 'root' ]; then
-        printf ${GREEN}"%s ${RED}command must be ran as root${ALL_OFF}\n" "$SCRIPTNAME"
-        exit
-    fi
+  if [ $runas != 'root' ]; then
+    printf ${GREEN}"%s ${RED}command must be ran as root${ALL_OFF}\n" "$SCRIPTNAME"
+    exit
+  fi
 
+  if ! command -v snaphome &>/dev/null; then
+    printf ${RED}"snaphome could not be found${ALL_OFF}\n"
+    exit
+  else
+    printf ${GREEN}"running pacman hook snaphome.${ALL_OFF}\n"
+    snaphome --pacman
+  fi
 
-    if ! command -v snaphome &> /dev/null; then
-        printf ${RED}"snaphome could not be found${ALL_OFF}\n"
-        exit
-    else
-        printf ${GREEN}"running pacman hook snaphome.${ALL_OFF}\n"
-        snaphome --pacman
-    fi
+  if ! command -v snaproot &>/dev/null; then
+    printf ${RED}"snaproot could not be found${ALL_OFF}\n"
+    exit
+  else
+    printf ${GREEN}"running pacman hook snaproot.${ALL_OFF}\n"
+    snaproot --pacman
+  fi
 
-    if ! command -v snaproot &> /dev/null; then
-        printf ${RED}"snaproot could not be found${ALL_OFF}\n"
-        exit
-    else
-        printf ${GREEN}"running pacman hook snaproot.${ALL_OFF}\n"
-        snaproot --pacman
-    fi
+  if ! command -v grub-mkconfig &>/dev/null; then
+    printf ${RED}"grub-mkconfig could not be found${ALL_OFF}\n"
+    exit
+  else
+    printf ${GREEN}"running pacman hook grub-mkconfig.${ALL_OFF}\n"
+    grub-mkconfig -o /boot/grub/grub.cfg
+  fi
 
-    if ! command -v grub-mkconfig &> /dev/null; then
-        printf ${RED}"grub-mkconfig could not be found${ALL_OFF}\n"
-        exit
-    else
-        printf ${GREEN}"running pacman hook grub-mkconfig.${ALL_OFF}\n"
-        grub-mkconfig -o /boot/grub/grub.cfg
-    fi
-
-    printf "\n"
-    read -rsn1 -p "Press any key to continue";printf "\n"
+  printf "\n"
+  read -rsn1 -p "Press any key to continue"
+  printf "\n"
 }
 
 #=== FUNCTION =================================================================
@@ -186,14 +209,14 @@ pacman() {
 #==============================================================================
 
 version() {
-    printf "
+  printf "
         %s v%s - %s
 
         This program may be freely redistributed under
         the terms of the GNU General Public License v3.0.
         %s
     \n" "$SCRIPTNAME" "$VERSION" "$DESCRIPTION" "$AUTHOR"
-    exit
+  exit
 }
 
 #=== FUNCTION =================================================================
@@ -203,7 +226,7 @@ version() {
 
 usage() {
 
-    printf "
+  printf "
     Snapshot the @ and @home btrfs subvolumes.
     Usage:
       %s...
@@ -218,39 +241,39 @@ usage() {
 }
 
 while true; do
-    case $1 in
-        -h|--help|-\?)
-            usage
-            exit 0
-            ;;
-        -v|--version)
-            version
-            exit 0
-            ;;
-        -p|--pacman)
-            pacman
-            exit 0
-            ;;
-        --home)
-            home_only
-            exit 0
-            ;;
-        --root)
-            root_only
-            exit 0
-            ;;
-        --)
-            shift
-            break
-            ;;
-        -*)
-            error "Unknown option: $1"
-            usage
-            exit 1
-            ;;
-        *)
-            main
-            break
-            ;;
-    esac
+  case $1 in
+  -h | --help | -\?)
+    usage
+    exit 0
+    ;;
+  -v | --version)
+    version
+    exit 0
+    ;;
+  -p | --pacman)
+    pacman
+    exit 0
+    ;;
+  --home)
+    home_only
+    exit 0
+    ;;
+  --root)
+    root_only
+    exit 0
+    ;;
+  --)
+    shift
+    break
+    ;;
+  -*)
+    error "Unknown option: $1"
+    usage
+    exit 1
+    ;;
+  *)
+    main
+    break
+    ;;
+  esac
 done
